apiVersion: v1
kind: Service
metadata:
  name: contacts-service
spec:
  type: NodePort                            # ▶️ exposes your app on every node’s IP
  selector:
    app: contacts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 30080                       # ▶️ fixed high-numbered port
