name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build & Run Tests
        run: mvn clean package --batch-mode

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Verify Snyk CLI
        run: snyk --version

      - name: Snyk Dependency & Vulnerability Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --sarif-file-output=snyk-dep.sarif || true

      - name: Snyk Code Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test --sarif-file-output=snyk-code.sarif || true

      - name: Snyk IaC Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk iac test --sarif-file-output=snyk-iac.sarif || true

      - name: Install snyk-to-sarif converter
        run: npm install -g snyk-to-sarif

      - name: Convert Dependency SARIF
        run: snyk-to-sarif -i snyk-dep.sarif -o snyk-dep-converted.sarif

      - name: Convert Code Quality SARIF
        run: snyk-to-sarif -i snyk-code.sarif -o snyk-code-converted.sarif

      - name: Convert IaC SARIF
        run: snyk-to-sarif -i snyk-iac.sarif -o snyk-iac-converted.sarif

      - name: Upload SARIF results (Dependencies)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-dep-converted.sarif

      - name: Upload SARIF results (Code Quality)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code-converted.sarif

      - name: Upload SARIF results (IaC)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-iac-converted.sarif

      - name: Upload raw SARIF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: raw-snyk-sarif
          path: |
            snyk-dep.sarif
            snyk-code.sarif
            snyk-iac.sarif

      - name: Upload converted SARIF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: converted-sarif
          path: |
            snyk-dep-converted.sarif
            snyk-code-converted.sarif
            snyk-iac-converted.sarif
